name: BankNLP
channels:
  - defaults
dependencies:
  - python=3.7
  - scikit-learn
  - numpy
  - pandas
  - matplotlib
  - gensim
  - requests
  - lxml
  - pip
  - pip:
    - pytablewriter
    - tabula
    - bs4
    - pdftotext # See following https://pypi.org/project/pdftotext/ Requires Microsoft Visual Studio Install
